Repository Certora/Documentation, pull requests merged in 2023-09, with the labels that each got.

#136 removed support for windows
  docs/user-guide/getting-started/install.md
Labels: bug

#140 [Proposal] reset storage syntax
  docs/cvl/expr.md
  docs/cvl/types.md
Labels: proposal

#130 DOC-317 Document catch-all summaries
  docs/cvl/methods.md
Labels: existing feature
