Repository Certora/Documentation, pull requests merged in 2024-03, with the labels that each got.

#221 Update timeout prevention docs for live stats [DOC-402]
  docs/user-guide/glossary.md
  docs/user-guide/timeouts/memory-complexity-field.png
  docs/user-guide/timeouts/nonlinear-ops-call.png
  docs/user-guide/timeouts/nonlinear-ops-field.png
  docs/user-guide/timeouts/path-count-stats.png
  docs/user-guide/timeouts/path-diamonds.png
  docs/user-guide/timeouts/timeouts-main.md
  spelling_wordlist.txt
Labels: existing feature

#217 CERT-4884 updated docs (pending v7 release)
  docs/cvl/methods.md
  docs/prover/cli/options.md
Labels: v7

#222 documenting autosummarizer, for v7
  docs/prover/cli/options.md
  docs/user-guide/timeouts/auto-summarizer-output-example.png
  docs/user-guide/timeouts/timeouts-main.md
Labels: v7

#224 document the change in default summarization policy for external wildcard summaries
  docs/cvl/methods.md
Labels: v7

#225 remove all mentions of STORAGE
  docs/confluence/anatomy/example.md
  docs/confluence/anatomy/ghosts.md
  docs/confluence/anatomy/hooks.md
  docs/confluence/anatomy/overview.md
  docs/confluence/map/ghosts.md
  docs/confluence/map/iterable.md
  docs/cvl/ghosts.md
  docs/cvl/hooks.md
  docs/cvl/v5-changes.md
  docs/user-guide/patterns/sums.md
  old/user-manual/advanced-subjects/ghosts/README.md
  old/user-manual/advanced-subjects/ghosts/a-complete-example-1.md
  old/user-manual/advanced-subjects/ghosts/hooks.md
  old/user-manual/advanced-subjects/ghosts/multi-contract-hooks.md
  old/user-manual/from-basic-to-advanced.md
  old/user-manual/specification/from-basic-to-advanced/an-iterable-map.md
  old/user-manual/specification/from-basic-to-advanced/an-iterable-map/README.md
  old/user-manual/specification/from-basic-to-advanced/an-iterable-map/verification-with-ghosts.md
  util/highlight.py
Labels: v7

#227 remove the 'STORAGE' keyword from hook documentation and document dynamic array length hook
  docs/confluence/anatomy/example.md
  docs/cvl/hooks.md
  old/user-manual/advanced-subjects/ghosts/a-complete-example-1.md
Labels: release, v7

#229 document struct comparison and remove string-interpolation docs
  docs/cvl/expr.md
  docs/cvl/rules.md
  docs/cvl/statements.md
Labels: release, v7

#231 update for compiler_map and hook on length
  docs/cvl/hooks.md
  docs/prover/cli/options.md
Labels: v7

#232 changelog v7
  docs/prover/changelog/prover_changelog.md
Labels: v7

#230 updated mutation docs to v7 DOC-411
  docs/gambit/gambit.md
  docs/gambit/mutation-verifier.md
Labels: release, v7

#237 changed optimistic_fallback description and removed the "required" true
  docs/prover/cli/options.md
Labels: existing feature

#238 Documentation for Out Of Memory Problems [DOC-386]
  docs/cvl/index.md
  docs/user-guide/index.md
  docs/user-guide/out-of-resources/auto-summarizer-output-example.png
  docs/user-guide/out-of-resources/hard-stop-in-report.png
  docs/user-guide/out-of-resources/index.md
  docs/user-guide/out-of-resources/memory-complexity-field.png
  docs/user-guide/out-of-resources/memout.md
  docs/user-guide/out-of-resources/nonlinear-ops-call.png
  docs/user-guide/out-of-resources/nonlinear-ops-field.png
  docs/user-guide/out-of-resources/path-count-stats.png
  docs/user-guide/out-of-resources/path-diamonds.png
  docs/user-guide/out-of-resources/rule-timeout-in-report.png
  docs/user-guide/out-of-resources/timeout-theory.md
  docs/user-guide/out-of-resources/timeout.md
  docs/user-guide/timeouts/index.md
Labels: existing feature
