Repository Certora/Documentation, pull requests merged in 2024-07, with the labels that each got.

#274 glossary entry for call trace (was: TODO)
  docs/prover/changelog/report_changelog.md
  docs/user-guide/glossary.md
Labels: existing feature

#263 Adding info about vacuousy for DISPATCHER(true)
  docs/cvl/methods.md
Labels: release

#266 Allow comparison of structs also when they contain bytes or string fields
  docs/cvl/expr.md
Labels: release

#268 Adding transient storage check in Invariant
  docs/cvl/invariants.md
Labels: release

#269 Updates due to complex types
  docs/cvl/methods.md
Labels: release

#272 update for new builtin sanity [DOC-425]
  docs/cvl/builtin.md
  docs/cvl/statements.md
  docs/prover/approx/index.md
  docs/prover/cli/options.md
  docs/user-guide/glossary.md
  docs/user-guide/satisfy.md
  spelling_wordlist.txt
Labels: release, existing feature

#275 2.1.7 report update
  docs/prover/changelog/report_changelog.md
Labels: release

#276 Remove duplicate descriptions of the `--method` flag
  docs/prover/cli/options.md
Labels: release

#270 update docs on inclusion of fallback in dispatch list summaries
  docs/cvl/methods.md
Labels: release

#281 sanity as sub rules DOC-426
  docs/prover/checking/implication_sanity_structure.png
  docs/prover/checking/sanity-details.png
  docs/prover/checking/sanity-icons.png
  docs/prover/checking/sanity.md
  docs/prover/checking/tautology_subrule.png
  docs/prover/checking/trivial_invariant_node.png
  docs/prover/checking/vacuity_node.png
Labels: release

#278 Documentation for Strong Invariants
  docs/cvl/invariants.md
Labels: release

#283 added changes
  docs/prover/changelog/prover_changelog.md
  spelling_wordlist.txt
Labels: release
