Repository Certora/Documentation, pull requests merged in 2024-02, with the labels that each got.

#195 DOC-378: Add text for changes in CERT-3967.
  docs/cvl/invariants.md
  docs/cvl/using.md
  util/highlight.py
Labels: future

#204 DOC-384: Add explanations on call hooks
  docs/cvl/hooks.md
Labels: existing feature

#212 Uri/solc select DOC-391
  docs/user-guide/getting-started/install.md
Labels: existing feature

#213 Uri/new note no gambit linux arm
  docs/gambit/gambit.md
  docs/gambit/mutation-verifier.md
Labels: existing feature

#215 added explanation about the dashboard and statuses DOC-393
  docs/gambit/doc/halted_mutation_test.png
  docs/gambit/doc/mutation_test_calculating.png
  docs/gambit/doc/mutation_test_executed.png
  docs/gambit/doc/mutation_test_problem.png
  docs/gambit/doc/mutation_test_started_dashboard.png
  docs/gambit/mutation-verifier.md
Labels: existing feature

#219 removing all references to -globalTimeout in favor of --global_timeout DOC-397 DOC-396
  docs/prover/cli/options.md
  docs/user-guide/timeouts/timeouts-main.md
Labels: cleanup, hiding features

#170 [DOC-355] Document TAC reports
  docs/prover/diagnosis/call-depth-arrows.png
  docs/prover/diagnosis/index.md
  docs/prover/diagnosis/rebase-tac-report-plain-annotated.png
  docs/prover/diagnosis/sat-tac-report-plain.png
  docs/prover/diagnosis/source-pointer-on-hover-annotated.png
  docs/prover/diagnosis/timeout-tac-report-explanation-box.png
  docs/prover/diagnosis/timeout-tac-report-green-nodes.png
  docs/prover/diagnosis/timeout-tac-report-overview.png
  docs/prover/diagnosis/timeout-tac-report-plain.png
  docs/prover/diagnosis/timeout-tac-report-source-code.png
  docs/prover/diagnosis/timeout-tac-report-yellow-nodes.png
  docs/user-guide/glossary.md
  docs/user-guide/index.md
  docs/whitepaper/index.md
  spelling_wordlist.txt
Labels: existing feature
