Repository Certora/Documentation, pull requests merged in 2024-04, with the labels that each got.

#236 [DOC-412] Added documentation about unresolved calls summarization
  docs/cvl/methods.md
Labels: release, v7.3.0

#242 document '--exclude_rule'
  docs/prover/cli/options.md
Labels: v7.3.0

#239 v7.2.0 additions
  docs/cvl/expr.md
  docs/cvl/hooks.md
  docs/cvl/index.md
  docs/cvl/transient.md
  docs/prover/cli/options.md
  spelling_wordlist.txt
Labels: v7.3.0

#235 v7.0.8 additions
  docs/prover/cli/options.md
Labels: v7.3.0

#233 Updating release note for rule report
  docs/prover/changelog/report_changelog.md
  spelling_wordlist.txt
Labels: release, v7.3.0

#247 changelog for v7.3.0
  docs/cvl/expr.md
  docs/prover/changelog/prover_changelog.md
  spelling_wordlist.txt
Labels: v7.3.0

#249 Redirecting old google broken link
  docs/user-guide/.htaccess
Labels: bug

#251 deleting now useless file
  docs/user-guide/.htaccess
Labels: cleanup

#246 DOC-415 | Add CI Configuration Guide
  conf.py
  docs/user-guide/ci.rst
  docs/user-guide/index.md
  requirements.txt
Labels: existing feature
