Repository Certora/Documentation, pull requests merged in 2024-01, with the labels that each got.

#188 added link to key signup, removed mentions of the free limited version DOC-165
  docs/user-guide/getting-started/install.md
Labels: existing feature

#186 [DOC-373] document optimistic_summary_recursion and summary_recursion_limit
  docs/prover/cli/options.md
Labels: existing feature

#187 [DOC-372] Direct storage havoc
  docs/cvl/expr.md
Labels: release

#191 document logical operator precedence
  docs/cvl/expr.md
Labels: existing feature

#178 [DOC-368] Added documentation to independent_satisfy mode
  docs/prover/cli/options.md
Labels: future

#194 CERT-3505: Adding docs for casting address to bytes32 and back.
  docs/cvl/cvl2/changes.md
  docs/cvl/expr.md
Labels: future

#185 [DOC-374] Fixes to certoraMutate docs CERT-4469 CERT-4589
  docs/cvl/ghosts.md
  docs/gambit/doc/email_mutation_success.png
  docs/gambit/doc/mutation_advanced_results.png
  docs/gambit/doc/mutation_metrics.png
  docs/gambit/doc/selecting_a_rule.png
  docs/gambit/doc/show_mutant_patch.png
  docs/gambit/index.md
  docs/gambit/mutation-verifier.md
Labels: existing feature

#200 added warning in documentation about trailing slash in remappings gambit
  docs/gambit/gambit.md
Labels: existing feature

#198 restructure timeouts main doc towards the main timeout statistics
  docs/user-guide/timeouts/timeouts-main.md
Labels: release

#164 [DOC-351] Document control flow splitting
  docs/prover/cli/options.md
  docs/prover/techniques/index.md
  docs/prover/techniques/split-step.png
  docs/user-guide/glossary.md
  docs/user-guide/timeouts/timeouts-main.md
  spelling_wordlist.txt
Labels: existing feature

#207 removed assert_contracts docs RMP-64
  docs/prover/cli/options.md
Labels: deprecated

#203 DOC-384: We can only hook once
  docs/cvl/hooks.md
Labels: existing feature
