Repository Certora/Documentation, pull requests merged in 2025-03, with the labels that each got.

#366 Update: Live stats now also talk about internal calls
  docs/user-guide/out-of-resources/timeout.md
Labels: release, existing feature

#368 release notes for v7.26.0
  docs/prover/changelog/gui_changelog.md
  docs/prover/changelog/prover_changelog.md
Labels: release

#371 Uri/remove allow solidity calls in quantifiers
  docs/cvl/v5-changes.md
  docs/prover/changelog/prover_changelog.md
  docs/prover/cli/options.md
Labels: cleanup

#372 removing lastHasThrown
  docs/cvl/expr.md
Labels: cleanup
