Repository Certora/Documentation, pull requests merged in 2025-02, with the labels that each got.

#345 CERT-8156: split_rules documentation
  docs/prover/cli/options.md
Labels: release

#351 Uri/solana docs review
  docs/solana/index.rst
  docs/solana/output.md
  docs/solana/sanity.md
  docs/solana/speclanguage.md
Labels: cleanup

#355 Uri/add GitHub syntax highlighting instructions
  docs/user-guide/assets/conf_before_highlighting.png
  docs/user-guide/assets/highlighted_conf.png
  docs/user-guide/assets/spec_with_highlighting.png
  docs/user-guide/assets/spec_without_highlighting.png
  docs/user-guide/github_highlighting.md
  docs/user-guide/index.md
  docs/user-guide/install.md
  docs/user-guide/running.rst
Labels: existing feature, cleanup

#331 update --method flag documentation
  docs/prover/cli/options.md
  spelling_wordlist.txt
Labels: release

#352 Document sum and usum
  docs/cvl/expr.md
  spelling_wordlist.txt
Labels: release

#333 added description for --disable_local_type_checking
  docs/prover/cli/options.md
Labels: release, existing feature

#356 Foundry Integration Doc Updates
  docs/cvl/foundry-integration.md
Labels: release

#327 Solana documentation
  docs/prover/checking/sanity.md
  docs/prover/cli/options.md
  docs/solana/img/call-trace-visual.svg
  docs/solana/img/call_trace_detail.png
  docs/solana/img/call_trace_example.png
  docs/solana/img/failed.png
  docs/solana/img/passed.png
  docs/solana/img/stack_access_error.png
  docs/solana/img/vacuity_check.png
  docs/solana/index.rst
  docs/solana/installation.md
  docs/solana/options.md
  docs/solana/output.md
  docs/solana/sanity.md
  docs/solana/scripts/justfile
  docs/solana/speclanguage.md
  docs/solana/troubleshooting.md
  docs/solana/usage.md
  docs/user-guide/index.md
  docs/user-guide/install.md
  docs/user-guide/install_evm_compiler.md
  index.rst
  spelling_wordlist.txt
Labels: release

#358 adding a subtitle for sums
  docs/cvl/expr.md
Labels: bug

#361 added changelog for 7.25.1
  docs/prover/changelog/gui_changelog.md
  docs/prover/changelog/prover_changelog.md
Labels: release

#359 first pass
  docs/prover/changelog/prover_changelog.md
  docs/prover/cli/options.md
Labels: cleanup

#362 formatting precise_bitwise_ops
  docs/prover/cli/options.md
Labels: cleanup
