Repository Certora/Documentation, pull requests merged in 2025-08, with the labels that each got.

#425 DOC-450: patches support in mutations
  docs/gambit/mutation-verifier.md
Labels: existing feature

#426 CERT-9396: documentation on remappings
  docs/prover/cli/conf-file-api.md
  docs/prover/cli/index.md
  docs/prover/cli/options.md
  docs/prover/cli/packages_and_remappings.md
Labels: release8.0

#354 CERT-8241: revert in cvl
  docs/cvl/statements.md
Labels: release8.0

#423 Update transient storage hooks
  docs/cvl/hooks.md
Labels: release8.0

#424 Yoav/cli breaking changes
  docs/equiv-check/index.md
  docs/prover/cli/options.md
  docs/solana/troubleshooting.md
  docs/sunbeam/installation.rst
  docs/sunbeam/troubleshooting.rst
  docs/user-guide/install.md
Labels: release8.0

#430 added changelog 1st version
  docs/prover/changelog/gui_changelog.md
  docs/prover/changelog/prover_changelog.md
Labels: release8.0

#429 Uri/update version 8 docs
  docs/cvl/statements.md
  docs/prover/checking/sanity.md
  docs/prover/cli/options.md
Labels: release8.0

#435 Clarify ghosts.md, DOC-406
  docs/cvl/expr.md
  docs/cvl/ghosts.md
  docs/prover/cli/options.md
  spelling_wordlist.txt
Labels: cleanup
