Repository Certora/Documentation, pull requests merged in 2025-04, with the labels that each got.

#374 Solana Livestats update
  docs/solana/output.md
  docs/user-guide/out-of-resources/timeout.md
  spelling_wordlist.txt
Labels: release

#376 7.28.0 gui release notes
  docs/prover/changelog/gui_changelog.md
Labels: release

#375 changelog for 7.27.2
  docs/prover/changelog/gui_changelog.md
  docs/prover/changelog/prover_changelog.md
Labels: release

#381 using smaller subtitles to hide from main nav menu
  docs/cvl/foundry-integration.md
  docs/prover/changelog/index.md
  docs/user-guide/out-of-resources/timeout-theory.md
  docs/user-guide/out-of-resources/timeout.md
  docs/whitepaper/index.md
  spelling_wordlist.txt
Labels: bug

#382 Remove static_assert and static_require as they are no longer supported
  docs/cvl/statements.md
Labels: cleanup

#383 Uri/gammar improvements 1
  .gitignore
  docs/user-guide/checking.md
  docs/user-guide/gaps.md
  docs/user-guide/out-of-resources/memout.md
  docs/user-guide/out-of-resources/timeout-theory.md
  docs/user-guide/out-of-resources/timeout.md
  spelling_wordlist.txt
Labels: cleanup

#384 removing unsupported/now hidden flags from cvl conversion guide from …
  docs/cvl/cvl2/changes.md
  docs/prover/cli/options.md
Labels: bug

#386 added --prover_version
  docs/prover/cli/options.md
Labels: bug

#387 Uri/improve solc attribute docs
  docs/prover/cli/options.md
Labels: cleanup

#389 trying the new format for --verify
  docs/prover/cli/options.md
Labels: existing feature, cleanup
