Repository Certora/Documentation, pull requests merged in 2025-05, with the labels that each got.

#401 added label for the flag --multi_example
  docs/prover/cli/options.md
Labels: cleanup

#380 Add require reason to statement grammar and explanation
  docs/cvl/statements.md
Labels: release

#393 Document `--exclude_rule`
  docs/prover/cli/options.md
Labels: release

#396 7.29.1 Release - Added FE changelog
  docs/prover/changelog/gui_changelog.md
  spelling_wordlist.txt
Labels: release

#399 added release notes for v7.29.0
  docs/prover/changelog/prover_changelog.md
Labels: release

#402 changelog version 7.29.0 -> 7.29.1
  docs/prover/changelog/prover_changelog.md
Labels: cleanup

#398 How Ranger Works
  docs/ranger/how_ranger_works.md
Labels: future

#397 Yoav/cert 8890 ranger cli docs
  docs/ranger/how_ranger_works.md
  docs/ranger/ranger_client.md
Labels: future
